/** Permanent guide aliases retained after the nested documentation reorganization. */
export const guideRedirects: Readonly<Record<string, string>> = {
	'framework/application-model': 'framework',
	'framework/app-macro': 'framework/application/app-macro',
	'framework/lifecycle-and-shutdown': 'framework/application/lifecycle',
	'framework/protocol-composition': 'framework/application/protocol-composition',
	'di/components': 'framework/dependency-injection/components',
	'di/advanced': 'framework/dependency-injection/advanced',
	'framework/configuration-sources': 'framework/configuration/sources-and-bindings',
	'framework/configuration-reload': 'framework/configuration/reload',
	'framework/features-and-targets': 'framework/platforms/features-and-targets',
	'framework/application-directories': 'framework/platforms/application-directories',
	'extensions/plugins': 'framework/extensions/plugins',
	'extensions/protocols/authoring': 'framework/extensions/protocol-authoring',
	'axum/request-context': 'axum/http/request-context',
	'axum/multipart-uploads': 'axum/http/multipart-uploads',
	'axum/streaming-http': 'axum/http/streaming',
	'axum/openapi': 'axum/http/openapi',
	'rpc/services': 'rpc/server',
	'rpc/server-policies': 'rpc/server/policies',
	'clients/native-http': 'clients/native/http',
	'clients/native-rpc': 'clients/native/rpc',
	'clients/native-websocket': 'clients/native/websocket',
	'clients/browser-wasm': 'clients/browser/setup-and-http',
	'cargo-upwell/inspect-and-graph': 'cargo-upwell/cli/inspect-and-graph',
	'cargo-upwell/automation-and-extensions': 'cargo-upwell/cli/automation-and-completions',
	'cargo-upwell/programmatic-probes': 'cargo-upwell/programmatic-api/discovery-and-probes',
	'cargo-upwell/programmatic-command-reports': 'cargo-upwell/programmatic-api/command-reports',
	'cargo-upwell/catalog-templates': 'cargo-upwell/catalog/templates',
	'cargo-upwell/catalog-extensions': 'cargo-upwell/catalog/extensions',
	'cargo-upwell/renderer-authoring': 'cargo-upwell/renderers/authoring',
	'cargo-upwell/renderer-testing-and-failures': 'cargo-upwell/renderers/testing-and-failures'
};
